# Generated by Django 3.1.1 on 2021-04-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamerMatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchform',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matchform',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
