# Generated by Django 3.1.7 on 2021-05-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamerMatch', '0003_personaltags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltags',
            name='slug',
        ),
    ]
