# Generated by Django 3.1.7 on 2021-06-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamerMatch', '0004_remove_personaltags_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchform',
            name='user',
            field=models.CharField(default='', max_length=150),
        ),
    ]
