# Generated by Django 3.1.4 on 2021-06-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamerMatch', '0005_auto_20210610_1645'),
        ('GamerMatch', '0005_auto_20210608_1808'),
    ]

    operations = [
    ]
