# Generated by Django 3.1.7 on 2021-06-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamerMatch', '0006_merge_20210617_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltags',
            name='tags',
        ),
        migrations.AddField(
            model_name='personaltags',
            name='tags',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
