# Generated by Django 3.1.7 on 2021-06-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamerMatch', '0007_auto_20210617_1822'),
        ('GamerMatch', '0006_merge_20210615_1811'),
    ]

    operations = [
    ]
