# Generated by Django 3.1.7 on 2021-06-17 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GamerMatch', '0008_merge_20210617_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lol', models.BooleanField(default=False)),
                ('minecraft', models.BooleanField(default=False)),
                ('smash', models.BooleanField(default=False)),
                ('valorant', models.BooleanField(default=False)),
                ('overwatch', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
