# Generated by Django 3.1.7 on 2021-06-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamerMatch', '0010_auto_20210619_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalgames',
            name='otros',
            field=models.BooleanField(default=False),
        ),
    ]
